-- Con esto el mes se muestra en español
-- (Si se ejecuta en SQL Developer ya se muestra por default en español)
ALTER SESSION SET NLS_DATE_LANGUAGE = 'SPANISH';

SELECT DISTINCT
    TO_CHAR(CLI.NUMRUN, '09G999G999') || '-' || UPPER(DVRUN) as RUT_CLIENTE,
    INITCAP(PNOMBRE || ' ' || SNOMBRE || ' ' || APPATERNO || ' ' || APMATERNO) AS NOMBRE_CLIENTE,
    TO_CHAR(FECHA_NACIMIENTO, 'DD "de" Month') as FECHA_NAC_CLIENTE,
    TO_CHAR(FECHA_INSCRIPCION, 'DD "de" Month') as  FECHA_INS_CLIENTE,
    NVL(CORREO, 'Sin Correo') as CORREO_CLIENTE,
    NVL(TO_CHAR(FONO_CONTACTO), 'Sin Fono Contacto') as FONO_CLIENTE
FROM CLIENTE CLI INNER JOIN TARJETA_CLIENTE TARCLI
ON(CLI.NUMRUN = TARCLI.NUMRUN)
INNER JOIN PAGO_MENSUAL_TARJETA_CLIENTE PAGCLI
ON(TARCLI.NRO_TARJETA = PAGCLI.NRO_TARJETA)
INNER JOIN FORMA_PAGO FORPAG
ON(PAGCLI.COD_FORMA_PAGO = FORPAG.COD_FORMA_PAGO)
ORDER BY
    RUT_CLIENTE ASC;

SELECT TABLE_NAME FROM ALL_TAB_COLUMNS WHERE COLUMN_NAME = 'COD_FORMA_PAGO';
SELECT TABLE_NAME FROM ALL_TAB_COLUMNS WHERE COLUMN_NAME = 'NUMRUN';