-- Con esto el mes se muestra en español
-- (Si se ejecuta en SQL Developer ya se muestra por default en español)
ALTER SESSION SET NLS_DATE_LANGUAGE = 'SPANISH';

SELECT DISTINCT
    TO_CHAR(CLI.NUMRUN, '09G999G999') || '-' || UPPER(DVRUN) as RUT_CLIENTE,
    INITCAP(PNOMBRE || ' ' || SNOMBRE || ' ' || APPATERNO || ' ' || APMATERNO) AS NOMBRE_CLIENTE,
    TO_CHAR(FECHA_NACIMIENTO, 'DD "de" Month "de" YYYY') as FECHA_NAC_CLIENTE,
    TO_CHAR(FECHA_INSCRIPCION, 'DD "de" Month "de" YYYY') as  FECHA_INS_CLIENTE,
    NVL(CORREO, 'Sin Correo') as CORREO_CLIENTE,
    NVL(TO_CHAR(FONO_CONTACTO), 'Sin Fono Contacto') as FONO_CLIENTE,
    NOMBRE_FORMA_PAGO AS FORMA_PAGO_CLI,
    COUNT(*) AS CANT_PAGOS,
    PAGCLI.FECHA_PAGO AS ULTIMO_PAGO
FROM CLIENTE CLI INNER JOIN TARJETA_CLIENTE TARCLI
ON(CLI.NUMRUN = TARCLI.NUMRUN)
INNER JOIN PAGO_MENSUAL_TARJETA_CLIENTE PAGCLI
ON(TARCLI.NRO_TARJETA = PAGCLI.NRO_TARJETA)
INNER JOIN FORMA_PAGO FORPAG
ON(PAGCLI.COD_FORMA_PAGO = FORPAG.COD_FORMA_PAGO)
GROUP BY
    CLI.NUMRUN, DVRUN, PNOMBRE, SNOMBRE, APPATERNO, APMATERNO, FECHA_NACIMIENTO, FECHA_INSCRIPCION, CORREO, FONO_CONTACTO, NOMBRE_FORMA_PAGO, FECHA_PAGO
ORDER BY
    FORMA_PAGO_CLI ASC;